### ISSUE TITLE
Unable to import Symantec App: Unexpected error while importing file JSONObject["fields"] is not a JSONArray

### ISSUE THREAD

**Issue by jjesse** [Forescout/eyeExtend-Connect#10]
Fully patched and up to date Forescout 8.2.2 build and up to date version of Connect. Unable to import the Symantec app.
Tried on personal lab and Skytap lab with same error message
Steps:
1. Navigate via Tools -> Options -> Connect
![image](https://user-images.githubusercontent.com/7634964/130126972-0d5c68b4-e9ba-4076-9a5a-dcd16a77cb9a.png)
2. Selected the Symantec Connect App
3. Received error message
![image](https://user-images.githubusercontent.com/7634964/130127031-1194778c-2464-4f85-8050-62ecaa064220.png)

This happens every time

**Comment by fs-connect** [comment]
I don't see such issue on connect_module r1.6.
