### ISSUE TITLE
Prometheus Install Issue

### ISSUE THREAD

**Issue by andrewchumchal** [Forescout/eyeExtend-Connect#12]
We're currently running version 8.2.2 with the latest hotfix. When I try to import the Prometheus Connect App. I received this error  

![image](https://user-images.githubusercontent.com/8008169/139476198-b9fa604a-cf21-43ec-bb28-d8e817b74d67.png)

**Comment by fs-connect** [comment]
This is the list of function calls from python are prohibited due to security concern. "print" is not allowed.
    
example_blacklist = set(["glob", "os", "exec", "subprocess", "sys", "open", "eval", "shutil", "pathlib", \
                             "io", "ctypes", "threading", "multiprocessing", "_thread", "dummy_threading", "_dummy_thread", \
                             "cmd", "trace", "traceback", "tracemalloc", "fcntl", "dns", "dnspython", "print"])
