### ISSUE TITLE
This module is written for Python 3.x but Connect uses 2.7.5

### ISSUE THREAD

**Issue by RtKelleher** [Forescout/eyeExtend-Connect#3]
Does the connect module use Virtual Environment or something?

The ADD test is written for Python 3.x as evidenced by the authors choice of modules (e.g. from urllib import request vs. urllib.urlopen) The current version is unable to run in the 2.7.5 environment. 

Please Advise

**Comment by forescout-spollock** [comment]
Connect requires python 3.  You will want to view the training video here:  https://www.youtube.com/watch?v=kFyLVD8q8yE&list=PL2HYJud3zBqcjUoiJzVG33_ubuRqv3crQ&index=2&t=18s
