### ISSUE TITLE
Increases CPU and Connections to Firewall

### ISSUE THREAD

**Issue by tastyfrankfurt** [Forescout/eyeExtend-Connect#5]
The API that is queried when performing a discovery pulls every single connected user, as a result every time there is a admission event the API is queried. This needs to be changed to a scheduled based pull as this is impacting the GlobalProtect environment we are running on.

https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-panorama-api/pan-os-xml-api-use-cases/show-and-manage-globalprotect-users-api

**Comment by fs-connect** [comment]
you have the option to disable polling completely. You can also control how often polling occurs. 
<img width="703" alt="Screen Shot 2020-11-25 at 9 06 13 AM" src="https://user-images.githubusercontent.com/62399390/100259821-80f3d880-2efd-11eb-8a79-f122bbdb64ed.png">

**Comment by tastyfrankfurt** [comment]
Agreed, we are looking in the wrong place, we seem to have reduced the behaviour by changing policy to discover devices connected via vpn on VPN Segments.  This has reduced the load on the management plane of the Palo Alto firewalls.
